name: MATLAB Tests
on: 
  pull_request:
    branches:
      - CI-test
      
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: |    
        export DISPLAY=:99
        Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & /home/aaron/Documents/Matlab/bin/matlab -nodesktop -nosplash -r "runTestsAndGenerateReport;exit;"


    - name: Upload Test Report
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: test_results.txt    

